import { useMemo, useState } from 'react';
export default function ArabicActivityPlayer({ payload, onComplete }) {
 const items=payload.items||[]; const [answers,setAnswers]=useState({}); const [done,setDone]=useState(false); const [flipped,setFlipped]=useState({});
 const choices=useMemo(()=>items.map(x=>x.answer).sort(()=>Math.random()-.5),[items]);
 if(!items.length)return <p className="rounded-2xl bg-slate-50 p-6 text-slate-500">لم يضف المعلم عناصر للنشاط بعد.</p>;
 if(payload.type==='flashcards')return <div><div className="grid gap-4 sm:grid-cols-2">{items.map((x,i)=><button key={i} type="button" onClick={()=>setFlipped(old=>({...old,[i]:!old[i]}))} className={`min-h-40 rounded-3xl border p-6 text-xl font-black ${flipped[i]?'border-emerald-300 bg-emerald-50 text-emerald-700':'border-blue-200 bg-blue-50 text-blue-700'}`}>{flipped[i]?x.answer||'—':x.prompt||'—'}<small className="mt-4 block text-xs opacity-60">اضغط لقلب البطاقة</small></button>)}</div><button type="button" onClick={()=>onComplete?.({score:items.length,total:items.length})} className="mt-5 rounded-xl bg-emerald-600 px-6 py-3 font-black text-white">أنهيت البطاقات</button></div>;
 const correct=items.reduce((sum,x,i)=>sum+((answers[i]||'').trim()===(x.answer||'').trim()?1:0),0);
 const finish=()=>{setDone(true);onComplete?.({score:correct,total:items.length})};
 const prompt=x=>payload.type==='fill'?(x.sentence||'').replace('____','……'):payload.type==='ordering'?`رتّب الكلمات: ${(x.prompt||'').split(' ').sort(()=>Math.random()-.5).join(' ـ ')}`:x.prompt;
 return <div><div className="space-y-4">{items.map((x,i)=>{const ok=(answers[i]||'').trim()===(x.answer||'').trim();return <div key={i} className={`rounded-2xl border p-5 ${done?(ok?'border-emerald-300 bg-emerald-50':'border-red-200 bg-red-50'):'border-slate-200 bg-white'}`}><p className="mb-3 text-lg font-black">{prompt(x)}</p>{payload.type==='matching'?<div className="flex flex-wrap gap-2">{choices.map(a=><button key={a} type="button" disabled={done} onClick={()=>setAnswers(old=>({...old,[i]:a}))} className={`min-h-11 rounded-xl border px-4 font-bold ${answers[i]===a?'border-blue-500 bg-blue-50 text-blue-700':'bg-white'}`}>{a}</button>)}</div>:<input disabled={done} value={answers[i]||''} onChange={e=>setAnswers(old=>({...old,[i]:e.target.value}))} className="form-control" placeholder={payload.type==='ordering'?'اكتب الجملة بالترتيب الصحيح':'اكتب الإجابة'}/>} {done&&<p className="mt-3 text-sm font-bold">الإجابة: {x.answer}</p>}</div>})}</div>{!done?<button type="button" onClick={finish} disabled={Object.keys(answers).length<items.length} className="mt-5 rounded-xl bg-blue-600 px-7 py-3 font-black text-white disabled:opacity-40">تحقق من الإجابات</button>:<p className="mt-5 text-lg font-black text-blue-700">نتيجتك: {correct} من {items.length}</p>}</div>;
}
