import {useState} from 'react';
import {Head,useForm,Link} from '@inertiajs/react';
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout';
import InputError from '@/Components/InputError';

const homeFields=[['hero_title','اسم المنصة (عربيتي)'],['hero_highlight','عنوان الهيرو (أنتِ تكتبينه)'],['hero_description','وصف الهيرو (أنتِ تكتبينه)','area'],['why_title','عنوان المميزات'],['why_description','وصف المميزات','area'],['about_badge','شارة لمحة عنا'],['about_title','عنوان لمحة عنا'],['about_description','نص لمحة عنا','area'],['cta_title','عنوان الدعوة'],['cta_description','وصف الدعوة','area'],['contact_email','البريد'],['contact_phone','الهاتف'],['contact_address','العنوان']];
const seoFields=[['site_name','اسم الموقع'],['default_meta_title','العنوان الافتراضي'],['default_meta_description','وصف محركات البحث','area'],['default_meta_keywords','الكلمات المفتاحية'],['og_image_url','صورة المشاركة']];
const googleFields=[['google_analytics_id','Google Analytics ID'],['google_analytics_property_id','GA Property ID'],['google_ads_aw_id','Google Ads ID'],['google_ads_conversion_label','Conversion Label'],['google_search_console_api_key','Search Console API Key'],['google_site_verification','Site Verification']];
export default function Settings({homepage,seo,google}){const [tab,setTab]=useState('homepage');const {data,setData,put,processing,errors}=useForm({section:'homepage',homepage,seo:{site_name:seo.site_name||'',default_meta_title:seo.default_meta_title||'',default_meta_description:seo.default_meta_description||'',default_meta_keywords:seo.default_meta_keywords||'',og_image_url:seo.og_image_url||''},google});const changeTab=x=>{setTab(x);setData('section',x)};const fields=tab==='homepage'?homeFields:tab==='seo'?seoFields:googleFields;return <AuthenticatedLayout header="إعدادات المنصة"><Head title="إعدادات المنصة"/><div className="mx-auto max-w-5xl"><div className="mb-6 flex flex-col justify-between gap-4 rounded-3xl bg-gradient-to-l from-sky-600 to-blue-700 p-6 text-white sm:flex-row sm:items-center"><div><h2 className="text-2xl font-black">كل إعدادات المنصة في مكان واحد</h2><p className="mt-2 text-sm text-blue-100">المحتوى، الظهور في البحث، وخدمات Google.</p></div><Link href="/" className="rounded-xl bg-white/15 px-5 py-3 text-center font-black">معاينة الموقع</Link></div><div className="grid gap-5 lg:grid-cols-[220px_1fr]"><nav className="h-fit rounded-2xl border border-slate-100 bg-white p-2 shadow-sm">{[['homepage','محتوى الموقع','النصوص والتواصل'],['seo','SEO','العناوين والمشاركة'],['google','Google','التحليلات والتحقق']].map(([key,title,hint])=><button key={key} onClick={()=>changeTab(key)} className={`mb-1 w-full rounded-xl px-4 py-3 text-right transition ${tab===key?'bg-blue-600 text-white':'hover:bg-slate-50'}`}><strong className="block">{title}</strong><small className={tab===key?'text-blue-100':'text-slate-400'}>{hint}</small></button>)}</nav><form onSubmit={e=>{e.preventDefault();put(route('settings.update'))}} className="rounded-2xl border border-slate-100 bg-white p-5 shadow-sm sm:p-7"><h3 className="mb-6 text-xl font-black">{tab==='homepage'?'محتوى الصفحة الرئيسية':tab==='seo'?'إعدادات محركات البحث':'ربط خدمات Google'}</h3><div className="grid gap-5 md:grid-cols-2">{fields.map(([key,label,type])=><label key={key} className={type==='area'?'md:col-span-2':''}><span className="text-sm font-bold text-slate-700">{label}</span>{type==='area'?<textarea rows="4" value={data[tab]?.[key]||''} onChange={e=>setData(tab,{...data[tab],[key]:e.target.value})} className="form-control mt-2"/>:<input value={data[tab]?.[key]||''} onChange={e=>setData(tab,{...data[tab],[key]:e.target.value})} className="form-control mt-2"/>}<InputError message={errors[`${tab}.${key}`]} className="mt-1"/></label>)}</div><button disabled={processing} className="mt-7 min-h-12 rounded-xl bg-blue-600 px-7 font-black text-white disabled:opacity-50">حفظ هذا القسم</button></form></div></div></AuthenticatedLayout>}
